Repository f5/unovis, pull requests merged in 2022-12, with the labels that each got.

#59 Website: Gallery navigation fix; copy tweaks
  packages/website/docs/intro.mdx
  packages/website/src/pages/gallery/index.tsx
  packages/website/src/pages/index.tsx
  packages/website/static/img/unovis-social.png
Labels: bug, enhancement

#60 New dev app using React and supporting hot refresh
  .github/workflows/pull_request.yml
  package.json
  packages/dev/licences.txt
  packages/dev/package-lock.json
  packages/dev/package.json
  packages/dev/public/favicon.svg
  packages/dev/public/index.html
  packages/dev/src/App.module.css
  packages/dev/src/App.tsx
  packages/dev/src/components/ExampleViewer/index.tsx
  packages/dev/src/components/ExampleViewer/style.module.css
  packages/dev/src/components/NavigationItem/index.tsx
  packages/dev/src/components/NavigationItem/style.module.css
  packages/dev/src/components/NavigationSideBar/index.tsx
  packages/dev/src/components/NavigationSideBar/style.module.css
  packages/dev/src/declarations.d.ts
  packages/dev/src/examples/index.ts
  packages/dev/src/examples/xy-components/area/basic-area/index.tsx
  packages/dev/src/examples/xy-components/stacked-bar/basic-stacked-bar/index.tsx
  packages/dev/src/index.tsx
  packages/dev/src/utils/array.ts
  packages/dev/src/utils/data.ts
  packages/dev/tsconfig.json
  packages/dev/webpack.config.js
  packages/ts/src/components.ts
  packages/ts/src/components/free-brush/index.ts
  packages/ts/src/containers.ts
  packages/ts/src/types.ts
  postinstall.sh
Labels: enhancement

#78 Component | TopoJSONMap: Preventing `scale` from being `NaN`
  packages/ts/src/components/topojson-map/index.ts
Labels: bug

#82 Component | LeafletFlowMap: Fixing the destroy function
  packages/ts/src/components/leaflet-flow-map/index.ts
Labels: bug

#83 Component | Graph: Add support for custom node fills
  packages/dev/src/examples/networks-and-flows/graph/graph-custom-fill/index.tsx
  packages/dev/src/utils/data.ts
  packages/ts/src/components/graph/modules/node/helper.ts
  packages/ts/src/components/graph/modules/node/index.ts
  packages/ts/src/utils/color.ts
Labels: bug, enhancement
