Repository f5/unovis, pull requests merged in 2023-05, with the labels that each got.

#192 Utils | Clone Deep: Fixing cloning of arrays
  packages/ts/src/utils/data.ts
Labels: fix

#193 Utils | Text: Preventing empty first line when the first word is too long
  packages/ts/src/utils/text.ts
Labels: fix

#197 Component | Axis: Calling `tickFormat` only for the actual ticks
  packages/ts/src/components/axis/index.ts
Labels: fix

#195 Container: Fixing Reize Observer configuration
  packages/ts/src/containers/single-container/index.ts
  packages/ts/src/core/container/index.ts
Labels: fix

#196 Utils | Text: Adding configurable force word break option
  packages/ts/src/types/text.ts
  packages/ts/src/utils/text.ts
Labels: enhancement, fix

#199 Component | Axis: Fixing `tickFormat` calling when `tickValues` are set explicitly
  packages/ts/src/components/axis/index.ts
  packages/ts/src/utils/data.ts
Labels: fix

#205 Component | LeafletMap: Add getExpandedCluster public method
  packages/dev/src/examples/maps/leaflet/leaflet-map-colorMap/index.tsx
  packages/ts/src/components/leaflet-map/index.ts
  packages/ts/src/components/leaflet-map/modules/utils.ts
  packages/ts/src/components/leaflet-map/types.ts
Labels: enhancement

#209 Core: Using native ResizeObserver when available
  packages/ts/src/components/leaflet-flow-map/index.ts
  packages/ts/src/components/leaflet-map/index.ts
  packages/ts/src/core/container/index.ts
  packages/ts/src/utils/resize-observer.ts
Labels: enhancement, fix

#210 Project: Updating Dagre packages to the latest version
  package-lock.json
  packages/ts/licences.txt
  packages/ts/package.json
Labels: fix

#212 Container | XY: Render right after initialization if there are axes or components with data
  packages/ts/src/containers/xy-container/index.ts
Labels: fix
